const LANGUAGES = {
    en: {
        startGame: "Start Game",
        exitGame: "Exit Game",
        languageSelect: "Select Language",
        shipPlacement: "SHIP PLACEMENT",
        firstPlayerReady: "First player get ready.\nPlayer two look away",
        secondPlayerReady: "Second player get ready.\nPlayer one look away",
        gamePhase: "Game phase",
        playerTurn: "Player {player}'s turn",
        controls: "Controls:",
        moveCursor: "Arrow keys: Move cursor",
        attack: "Enter: Attack",
        gameOver: "Game Over",
        carrier: "Carrier",
        battleship: "Battleship",
        cruiser: "Cruiser",
        submarine: "Submarine",
        destroyer: "Destroyer",
        controls: "Controls:",
        arrowKeys: "Arrow keys: Move cursor",
        rotateShip: "R: Rotate ship",
        enter: "Enter: Place ship",
        shipsToPlace: "Ships to place: ",
        spaces: "spaces",
        shipPlacementPhase: "Ship placement phase",
        player1wins: "Player 1 wins!",
        player2wins: "Player 2 wins!",
    },
    es: {
        startGame: "Iniciar Juego",
        exitGame: "Salir del Juego",
        languageSelect: "Seleccionar Idioma",
        shipPlacement: "COLOCACIÓN DE BARCOS",
        firstPlayerReady: "Primer jugador prepárate.\nJugador dos mira hacia otro lado",
        secondPlayerReady: "Segundo jugador prepárate.\nJugador uno mira hacia otro lado",
        gamePhase: "Fase del juego",
        playerTurn: "Turno del jugador {player}",
        controls: "Controles:",
        moveCursor: "Teclas de flecha: Mover cursor",
        attack: "Enter: Atacar",
        gameOver: "Juego Terminado",
        carrier: "Portaaviones",
        battleship: "Acorazado",
        cruiser: "Crucero",
        submarine: "Submarino",
        destroyer: "Destructor",
        controls: "Controles:",
        arrowKeys: "Teclas de flecha: Mover cursor",
        rotateShip: "R: Rotar barco",
        enter: "Enter: Colocar barco",
        shipsToPlace: "Barcos para colocar: ",
        spaces: "espacios",
        shipPlacementPhase: "Fase de colocación de barcos",
        player1wins: "¡Jugador 1 gana!",
        player2wins: "¡Jugador 2 gana!",
    },
    no: {
        startGame: "Start spill",
        exitGame: "Avslutt spill",
        languageSelect: "Velg språk",
        shipPlacement: "SKIP PLASSERING",
        firstPlayerReady: "Første spiller klar.\nSpiller to ser bort",
        secondPlayerReady: "Andre spiller klar.\nSpiller en ser bort",
        gamePhase: "Spillfase",
        playerTurn: "Spiller {player}'s tur",
        controls: "Kontroller:",
        moveCursor: "Piltaster: Flytt markøren",
        attack: "Enter: Angrip",
        gameOver: "Spillet er over",
        carrier: "Hangarskip",
        battleship: "Slagskip",
        cruiser: "Krysser",
        submarine: "Undervannsbåt",
        destroyer: "Jager",
        controls: "Kontroller:",
        arrowKeys: "Piltaster: Flytt markøren",
        rotateShip: "R: Roter skip",
        enter: "Enter: Plasser skip",
        shipsToPlace: "Skip å plassere: ",
        spaces: "plasser",
        shipPlacementPhase: "Skip plasseringsfase",
        player1wins: "Spiller 1 vinner!",
        player2wins: "Spiller 2 vinner!",
    },
    se: {
        startGame: "Starta spel",
        exitGame: "Avsluta spel",
        languageSelect: "Välj språk",
        shipPlacement: "SKEPP PLACERING",
        firstPlayerReady: "Första spelaren redo.\nSpelare två titta bort",
        secondPlayerReady: "Andra spelaren redo.\nSpelare ett titta bort",
        gamePhase: "Spelfas",
        playerTurn: "Spelare {player}'s tur",
        controls: "Kontroller:",
        moveCursor: "Piltangenter: Flytta markören",
        attack: "Enter: Attackera",
        gameOver: "Spelet är över",
        carrier: "Hangarfartyg",
        battleship: "Slagskepp",
        cruiser: "Kryssare",
        submarine: "Ubåt",
        destroyer: "Jagare",
        controls: "Kontroller:",
        arrowKeys: "Piltangenter: Flytta markören",
        rotateShip: "R: Rotera skepp",
        enter: "Enter: Placera skepp",
        shipsToPlace: "Skepp att placera: ",
        spaces: "platser",
        shipPlacementPhase: "Skepp placering fas",
        player1wins: "Spelare 1 vinner!",
        player2wins: "Spelare 2 vinner!",
    },
};

export default LANGUAGES;